#!/usr/bin/env python3
"""
FINAL RESEARCH SEO MIGRATION

Reads definitive_publication_map.md generated by the audited workflow and:
1) updates sitemap.xml to contain exactly one canonical URL per mapped
   duplicate publication group, while preserving existing standalone article
   URLs;
2) writes/updates a managed .htaccess block with direct 301s for all legacy
   article folders and /index.html variants;
3) does NOT delete article directories or HTML files.

The migration is designed to be idempotent.
"""

from __future__ import annotations
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAP = ROOT / "definitive_publication_map.md"
SITEMAP = ROOT / "sitemap.xml"
HTACCESS = ROOT / ".htaccess"

BEGIN = "# BEGIN NUTRECONCIENCIA FINAL ARTICLE CANONICAL REDIRECTS"
END = "# END NUTRECONCIENCIA FINAL ARTICLE CANONICAL REDIRECTS"


def parse_map(text: str):
    canonicals = set()
    redirects = []
    for line in text.splitlines():
        m = re.match(r"\|\s*\d+\s*\|\s*`[^`]+`\s*\|\s*`([^`]+)`\s*\|", line)
        if m:
            slug = m.group(1)
            canonicals.add(slug)
        m2 = re.match(r"- `/articulos/([^/]+)/` → `https://nutreconciencia\.com/articulos/([^/]+)/`", line)
        if m2 and m2.group(1) != m2.group(2):
            redirects.append((m2.group(1), m2.group(2)))
    # Deduplicate.
    redirects = sorted(set(redirects))
    return canonicals, redirects


def update_sitemap(canonical_slugs: set[str]):
    if not SITEMAP.exists():
        raise FileNotFoundError("sitemap.xml no existe")
    text = SITEMAP.read_text(encoding="utf-8", errors="ignore")

    # Remove all existing /articulos/<slug>/ URLs, leaving the rest of the sitemap.
    pattern = re.compile(
        r"\s*<url>\s*<loc>https://nutreconciencia\.com/articulos/[^<]+</loc>\s*</url>",
        re.I,
    )
    text_without_articles = pattern.sub("", text)

    # Insert canonical article URLs before </urlset>.
    entries = []
    for slug in sorted(canonical_slugs):
        entries.append(
            f"  <url><loc>https://nutreconciencia.com/articulos/{slug}/</loc></url>"
        )
    block = "\n" + "\n".join(entries) + "\n"

    if re.search(r"</urlset>\s*$", text_without_articles, re.I):
        text_new = re.sub(
            r"</urlset>\s*$",
            block + "</urlset>",
            text_without_articles,
            flags=re.I,
        )
    else:
        raise ValueError("sitemap.xml no termina en </urlset>")

    SITEMAP.write_text(text_new, encoding="utf-8")


def build_htaccess(redirects):
    existing = HTACCESS.read_text(encoding="utf-8") if HTACCESS.exists() else ""

    # Strip prior final migration block, leaving all other existing rules intact.
    existing = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        "",
        existing,
        flags=re.S,
    ).strip()

    rules = [
        BEGIN,
        "RewriteEngine On",
        "",
        "# Canonicalize root/section index URLs",
        "Redirect 301 /index.html /",
        "Redirect 301 /articulos/index.html /articulos/",
        "Redirect 301 /prensa/index.html /prensa/",
        "Redirect 301 /libro/index.html /libro/",
        "Redirect 301 /sobre-mi/index.html /sobre-mi/",
        "Redirect 301 /podcasts/index.html /podcasts/",
        "",
        "# Direct legacy article redirects, including /index.html.",
    ]

    for old_slug, new_slug in redirects:
        rules.append(
            f"Redirect 301 /articulos/{old_slug}/ /articulos/{new_slug}/"
        )
        rules.append(
            f"Redirect 301 /articulos/{old_slug}/index.html /articulos/{new_slug}/"
        )

    rules.append(END)
    block = "\n".join(rules)

    final = (existing + "\n\n" + block).strip() + "\n"
    HTACCESS.write_text(final, encoding="utf-8")


def main():
    canonicals, redirects = parse_map(MAP.read_text(encoding="utf-8"))
    if not canonicals:
        raise RuntimeError("No se encontraron canónicas en definitive_publication_map.md")

    update_sitemap(canonicals)
    build_htaccess(redirects)

    print("=" * 72)
    print("FINAL RESEARCH SEO MIGRATION")
    print("=" * 72)
    print(f"Canonical article URLs in sitemap: {len(canonicals)}")
    print(f"Legacy redirect mappings: {len(redirects)}")
    print("Updated: sitemap.xml")
    print("Updated: .htaccess")
    print("No article directories or HTML files were deleted.")
    print("Migration is idempotent.")


if __name__ == "__main__":
    main()
